(function() {
    "use strict";
    angular.module("practice.error")
           .config(route);

    // always use $inject to make functions minify-able
    // @see https://docs.angularjs.org/guide/di
    route.$inject = ["$stateProvider", "$urlRouterProvider"];

    function route($stateProvider, $urlRouterProvider) {
        // create a url route
        // @see https://angular-ui.github.io/ui-router/site/
        $stateProvider.state("error", {
            url: "/error",
            // don't use a template file, get it from '$templateCache' instead
            templateProvider: getTemplate
        });

        // route every unknown request to error page
        // @see https://docs.angularjs.org/api/ngRoute/provider/$routeProvider
        $urlRouterProvider.otherwise("/error");

        // always use $inject to make functions minify-able
        // @see https://docs.angularjs.org/guide/di
        getTemplate.$inject = ["$templateCache"];

        /**
         * get template from cache
         * @param {$templateCache} $templateCache
         * @returns string
         */
        function getTemplate($templateCache) {
            // template cache will be generated by gulp -> gulpfile.js
            // @see https://docs.angularjs.org/api/ng/service/$templateCache
            return $templateCache.get("examples/error/error.tpl.html");
        }
    }
}());
