(function() {
    "use strict";
    angular.module("practice.directives")
           .config(route);

    // always use $inject to make functions minify-able
    // @see https://docs.angularjs.org/guide/di
    route.$inject = ["$stateProvider"];

    function route($stateProvider) {
        // create a url route
        // @see https://angular-ui.github.io/ui-router/site/
        $stateProvider.state("directives", {
            url: "/directives",
            // don't use a template file, get it from '$templateCache' instead
            templateProvider: getTemplate
        });

        // always use $inject to make functions minify-able
        // @see https://docs.angularjs.org/guide/di
        getTemplate.$inject = ["$templateCache"];

        /**
         * get template from cache
         * @param {$templateCache} $templateCache
         * @returns string
         */
        function getTemplate($templateCache) {
            // template cache will be generated by gulp -> gulpfile.js
            // @see https://docs.angularjs.org/api/ng/service/$templateCache
            return $templateCache.get("examples/directives/directives.tpl.html");
        }
    }
}());
